"""empty message

Revision ID: 82eac977fe33
Revises: cb0e90ac778c
Create Date: 2022-03-13 16:56:21.729333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82eac977fe33'
down_revision = 'cb0e90ac778c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
