"""empty message

Revision ID: e650f51f49ea
Revises: 82eac977fe33
Create Date: 2022-03-13 16:59:23.581506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e650f51f49ea'
down_revision = '82eac977fe33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
